all:
  children:

    slurm_controller:
      hosts:
        slurmctld:
          ansible_connection: docker
          ansible_user: root

    slurm_dbd:
      hosts:
        slurmdbd:
          ansible_connection: docker
          ansible_user: root

    compute:
      hosts:
        node01:
          ansible_connection: docker
          ansible_user: root
        node02:
          ansible_connection: docker
          ansible_user: root
        node03:
          ansible_connection: docker
          ansible_user: root

    monitoring:
      hosts:
        prometheus:
          ansible_connection: docker
          ansible_user: root

    ondemand:
      hosts:
        ood:
          ansible_connection: docker
          ansible_user: root
